# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent_runtime.v1 import agent_runtime_pb2 as agent__runtime_dot_v1_dot_agent__runtime__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_runtime/v1/agent_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeServiceStub:
    """AgentRuntimeService executes one immutable Agent turn. Cross-Agent selection,
    dialogue continuation, persistence, and room broadcasting remain Go concerns.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAgent = channel.unary_stream(
                '/agentroom.runtime.v1.AgentRuntimeService/ExecuteAgent',
                request_serializer=agent__runtime_dot_v1_dot_agent__runtime__pb2.ExecuteAgentRequest.SerializeToString,
                response_deserializer=agent__runtime_dot_v1_dot_agent__runtime__pb2.AgentEvent.FromString,
                _registered_method=True)


class AgentRuntimeServiceServicer:
    """AgentRuntimeService executes one immutable Agent turn. Cross-Agent selection,
    dialogue continuation, persistence, and room broadcasting remain Go concerns.
    """

    def ExecuteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=agent__runtime_dot_v1_dot_agent__runtime__pb2.ExecuteAgentRequest.FromString,
                    response_serializer=agent__runtime_dot_v1_dot_agent__runtime__pb2.AgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentroom.runtime.v1.AgentRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentroom.runtime.v1.AgentRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntimeService:
    """AgentRuntimeService executes one immutable Agent turn. Cross-Agent selection,
    dialogue continuation, persistence, and room broadcasting remain Go concerns.
    """

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentroom.runtime.v1.AgentRuntimeService/ExecuteAgent',
            agent__runtime_dot_v1_dot_agent__runtime__pb2.ExecuteAgentRequest.SerializeToString,
            agent__runtime_dot_v1_dot_agent__runtime__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
