// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: collaboration_runtime/v1/collaboration_runtime.proto

package collaborationruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollaborationRuntimeService_GetCapabilities_FullMethodName     = "/agentroom.collaboration.v1.CollaborationRuntimeService/GetCapabilities"
	CollaborationRuntimeService_ExecuteConversation_FullMethodName = "/agentroom.collaboration.v1.CollaborationRuntimeService/ExecuteConversation"
)

// CollaborationRuntimeServiceClient is the client API for CollaborationRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CollaborationRuntimeService executes one immutable, multi-turn room
// collaboration. Go remains responsible for persistence and broadcasting.
type CollaborationRuntimeServiceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	ExecuteConversation(ctx context.Context, in *ExecuteConversationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CollaborationEvent], error)
}

type collaborationRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollaborationRuntimeServiceClient(cc grpc.ClientConnInterface) CollaborationRuntimeServiceClient {
	return &collaborationRuntimeServiceClient{cc}
}

func (c *collaborationRuntimeServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, CollaborationRuntimeService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collaborationRuntimeServiceClient) ExecuteConversation(ctx context.Context, in *ExecuteConversationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CollaborationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollaborationRuntimeService_ServiceDesc.Streams[0], CollaborationRuntimeService_ExecuteConversation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteConversationRequest, CollaborationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollaborationRuntimeService_ExecuteConversationClient = grpc.ServerStreamingClient[CollaborationEvent]

// CollaborationRuntimeServiceServer is the server API for CollaborationRuntimeService service.
// All implementations must embed UnimplementedCollaborationRuntimeServiceServer
// for forward compatibility.
//
// CollaborationRuntimeService executes one immutable, multi-turn room
// collaboration. Go remains responsible for persistence and broadcasting.
type CollaborationRuntimeServiceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	ExecuteConversation(*ExecuteConversationRequest, grpc.ServerStreamingServer[CollaborationEvent]) error
	mustEmbedUnimplementedCollaborationRuntimeServiceServer()
}

// UnimplementedCollaborationRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollaborationRuntimeServiceServer struct{}

func (UnimplementedCollaborationRuntimeServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedCollaborationRuntimeServiceServer) ExecuteConversation(*ExecuteConversationRequest, grpc.ServerStreamingServer[CollaborationEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteConversation not implemented")
}
func (UnimplementedCollaborationRuntimeServiceServer) mustEmbedUnimplementedCollaborationRuntimeServiceServer() {
}
func (UnimplementedCollaborationRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeCollaborationRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollaborationRuntimeServiceServer will
// result in compilation errors.
type UnsafeCollaborationRuntimeServiceServer interface {
	mustEmbedUnimplementedCollaborationRuntimeServiceServer()
}

func RegisterCollaborationRuntimeServiceServer(s grpc.ServiceRegistrar, srv CollaborationRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCollaborationRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollaborationRuntimeService_ServiceDesc, srv)
}

func _CollaborationRuntimeService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollaborationRuntimeServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollaborationRuntimeService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollaborationRuntimeServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollaborationRuntimeService_ExecuteConversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteConversationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollaborationRuntimeServiceServer).ExecuteConversation(m, &grpc.GenericServerStream[ExecuteConversationRequest, CollaborationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollaborationRuntimeService_ExecuteConversationServer = grpc.ServerStreamingServer[CollaborationEvent]

// CollaborationRuntimeService_ServiceDesc is the grpc.ServiceDesc for CollaborationRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollaborationRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentroom.collaboration.v1.CollaborationRuntimeService",
	HandlerType: (*CollaborationRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _CollaborationRuntimeService_GetCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteConversation",
			Handler:       _CollaborationRuntimeService_ExecuteConversation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collaboration_runtime/v1/collaboration_runtime.proto",
}
