// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: agent_runtime/v1/agent_runtime.proto

package agentruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntimeService_ExecuteAgent_FullMethodName = "/agentroom.runtime.v1.AgentRuntimeService/ExecuteAgent"
)

// AgentRuntimeServiceClient is the client API for AgentRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRuntimeService executes one immutable Agent turn. Cross-Agent selection,
// dialogue continuation, persistence, and room broadcasting remain Go concerns.
type AgentRuntimeServiceClient interface {
	ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error)
}

type agentRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeServiceClient(cc grpc.ClientConnInterface) AgentRuntimeServiceClient {
	return &agentRuntimeServiceClient{cc}
}

func (c *agentRuntimeServiceClient) ExecuteAgent(ctx context.Context, in *ExecuteAgentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[0], AgentRuntimeService_ExecuteAgent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteAgentRequest, AgentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ExecuteAgentClient = grpc.ServerStreamingClient[AgentEvent]

// AgentRuntimeServiceServer is the server API for AgentRuntimeService service.
// All implementations must embed UnimplementedAgentRuntimeServiceServer
// for forward compatibility.
//
// AgentRuntimeService executes one immutable Agent turn. Cross-Agent selection,
// dialogue continuation, persistence, and room broadcasting remain Go concerns.
type AgentRuntimeServiceServer interface {
	ExecuteAgent(*ExecuteAgentRequest, grpc.ServerStreamingServer[AgentEvent]) error
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

// UnimplementedAgentRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServiceServer struct{}

func (UnimplementedAgentRuntimeServiceServer) ExecuteAgent(*ExecuteAgentRequest, grpc.ServerStreamingServer[AgentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteAgent not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) mustEmbedUnimplementedAgentRuntimeServiceServer() {}
func (UnimplementedAgentRuntimeServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServiceServer will
// result in compilation errors.
type UnsafeAgentRuntimeServiceServer interface {
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

func RegisterAgentRuntimeServiceServer(s grpc.ServiceRegistrar, srv AgentRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntimeService_ServiceDesc, srv)
}

func _AgentRuntimeService_ExecuteAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteAgentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentRuntimeServiceServer).ExecuteAgent(m, &grpc.GenericServerStream[ExecuteAgentRequest, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ExecuteAgentServer = grpc.ServerStreamingServer[AgentEvent]

// AgentRuntimeService_ServiceDesc is the grpc.ServiceDesc for AgentRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentroom.runtime.v1.AgentRuntimeService",
	HandlerType: (*AgentRuntimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteAgent",
			Handler:       _AgentRuntimeService_ExecuteAgent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_runtime/v1/agent_runtime.proto",
}
