// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0
// source: agent_runtime/v1/agent_runtime.proto

package agentruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutorKind int32

const (
	ExecutorKind_EXECUTOR_KIND_UNSPECIFIED ExecutorKind = 0
	ExecutorKind_EXECUTOR_KIND_LLM         ExecutorKind = 1
	ExecutorKind_EXECUTOR_KIND_DEEPAGENT   ExecutorKind = 2
)

// Enum value maps for ExecutorKind.
var (
	ExecutorKind_name = map[int32]string{
		0: "EXECUTOR_KIND_UNSPECIFIED",
		1: "EXECUTOR_KIND_LLM",
		2: "EXECUTOR_KIND_DEEPAGENT",
	}
	ExecutorKind_value = map[string]int32{
		"EXECUTOR_KIND_UNSPECIFIED": 0,
		"EXECUTOR_KIND_LLM":         1,
		"EXECUTOR_KIND_DEEPAGENT":   2,
	}
)

func (x ExecutorKind) Enum() *ExecutorKind {
	p := new(ExecutorKind)
	*p = x
	return p
}

func (x ExecutorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_runtime_v1_agent_runtime_proto_enumTypes[0].Descriptor()
}

func (ExecutorKind) Type() protoreflect.EnumType {
	return &file_agent_runtime_v1_agent_runtime_proto_enumTypes[0]
}

func (x ExecutorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutorKind.Descriptor instead.
func (ExecutorKind) EnumDescriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{0}
}

type SenderType int32

const (
	SenderType_SENDER_TYPE_UNSPECIFIED SenderType = 0
	SenderType_SENDER_TYPE_HUMAN       SenderType = 1
	SenderType_SENDER_TYPE_AGENT       SenderType = 2
	SenderType_SENDER_TYPE_SYSTEM      SenderType = 3
)

// Enum value maps for SenderType.
var (
	SenderType_name = map[int32]string{
		0: "SENDER_TYPE_UNSPECIFIED",
		1: "SENDER_TYPE_HUMAN",
		2: "SENDER_TYPE_AGENT",
		3: "SENDER_TYPE_SYSTEM",
	}
	SenderType_value = map[string]int32{
		"SENDER_TYPE_UNSPECIFIED": 0,
		"SENDER_TYPE_HUMAN":       1,
		"SENDER_TYPE_AGENT":       2,
		"SENDER_TYPE_SYSTEM":      3,
	}
)

func (x SenderType) Enum() *SenderType {
	p := new(SenderType)
	*p = x
	return p
}

func (x SenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_runtime_v1_agent_runtime_proto_enumTypes[1].Descriptor()
}

func (SenderType) Type() protoreflect.EnumType {
	return &file_agent_runtime_v1_agent_runtime_proto_enumTypes[1]
}

func (x SenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderType.Descriptor instead.
func (SenderType) EnumDescriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{1}
}

type RunErrorCode int32

const (
	RunErrorCode_RUN_ERROR_CODE_UNSPECIFIED                 RunErrorCode = 0
	RunErrorCode_RUN_ERROR_CODE_INVALID_REQUEST             RunErrorCode = 1
	RunErrorCode_RUN_ERROR_CODE_MODEL_NOT_CONFIGURED        RunErrorCode = 2
	RunErrorCode_RUN_ERROR_CODE_MODEL_AUTHENTICATION_FAILED RunErrorCode = 3
	RunErrorCode_RUN_ERROR_CODE_MODEL_RATE_LIMITED          RunErrorCode = 4
	RunErrorCode_RUN_ERROR_CODE_MODEL_TIMEOUT               RunErrorCode = 5
	RunErrorCode_RUN_ERROR_CODE_CANCELLED                   RunErrorCode = 6
	RunErrorCode_RUN_ERROR_CODE_TOOL_FAILED                 RunErrorCode = 7
	RunErrorCode_RUN_ERROR_CODE_OUTPUT_INVALID              RunErrorCode = 8
	RunErrorCode_RUN_ERROR_CODE_RESOURCE_EXHAUSTED          RunErrorCode = 9
	RunErrorCode_RUN_ERROR_CODE_EXECUTOR_UNAVAILABLE        RunErrorCode = 10
	RunErrorCode_RUN_ERROR_CODE_PROTOCOL_ERROR              RunErrorCode = 11
	RunErrorCode_RUN_ERROR_CODE_INTERNAL                    RunErrorCode = 12
)

// Enum value maps for RunErrorCode.
var (
	RunErrorCode_name = map[int32]string{
		0:  "RUN_ERROR_CODE_UNSPECIFIED",
		1:  "RUN_ERROR_CODE_INVALID_REQUEST",
		2:  "RUN_ERROR_CODE_MODEL_NOT_CONFIGURED",
		3:  "RUN_ERROR_CODE_MODEL_AUTHENTICATION_FAILED",
		4:  "RUN_ERROR_CODE_MODEL_RATE_LIMITED",
		5:  "RUN_ERROR_CODE_MODEL_TIMEOUT",
		6:  "RUN_ERROR_CODE_CANCELLED",
		7:  "RUN_ERROR_CODE_TOOL_FAILED",
		8:  "RUN_ERROR_CODE_OUTPUT_INVALID",
		9:  "RUN_ERROR_CODE_RESOURCE_EXHAUSTED",
		10: "RUN_ERROR_CODE_EXECUTOR_UNAVAILABLE",
		11: "RUN_ERROR_CODE_PROTOCOL_ERROR",
		12: "RUN_ERROR_CODE_INTERNAL",
	}
	RunErrorCode_value = map[string]int32{
		"RUN_ERROR_CODE_UNSPECIFIED":                 0,
		"RUN_ERROR_CODE_INVALID_REQUEST":             1,
		"RUN_ERROR_CODE_MODEL_NOT_CONFIGURED":        2,
		"RUN_ERROR_CODE_MODEL_AUTHENTICATION_FAILED": 3,
		"RUN_ERROR_CODE_MODEL_RATE_LIMITED":          4,
		"RUN_ERROR_CODE_MODEL_TIMEOUT":               5,
		"RUN_ERROR_CODE_CANCELLED":                   6,
		"RUN_ERROR_CODE_TOOL_FAILED":                 7,
		"RUN_ERROR_CODE_OUTPUT_INVALID":              8,
		"RUN_ERROR_CODE_RESOURCE_EXHAUSTED":          9,
		"RUN_ERROR_CODE_EXECUTOR_UNAVAILABLE":        10,
		"RUN_ERROR_CODE_PROTOCOL_ERROR":              11,
		"RUN_ERROR_CODE_INTERNAL":                    12,
	}
)

func (x RunErrorCode) Enum() *RunErrorCode {
	p := new(RunErrorCode)
	*p = x
	return p
}

func (x RunErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_runtime_v1_agent_runtime_proto_enumTypes[2].Descriptor()
}

func (RunErrorCode) Type() protoreflect.EnumType {
	return &file_agent_runtime_v1_agent_runtime_proto_enumTypes[2]
}

func (x RunErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunErrorCode.Descriptor instead.
func (RunErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{2}
}

type RoomSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DialogueMode  string                 `protobuf:"bytes,3,opt,name=dialogue_mode,json=dialogueMode,proto3" json:"dialogue_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSnapshot) Reset() {
	*x = RoomSnapshot{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSnapshot) ProtoMessage() {}

func (x *RoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSnapshot.ProtoReflect.Descriptor instead.
func (*RoomSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RoomSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomSnapshot) GetDialogueMode() string {
	if x != nil {
		return x.DialogueMode
	}
	return ""
}

type AgentSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mention        string                 `protobuf:"bytes,3,opt,name=mention,proto3" json:"mention,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	SystemPrompt   string                 `protobuf:"bytes,6,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Runtime        string                 `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ModelProfileId string                 `protobuf:"bytes,8,opt,name=model_profile_id,json=modelProfileId,proto3" json:"model_profile_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentSnapshot) Reset() {
	*x = AgentSnapshot{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSnapshot) ProtoMessage() {}

func (x *AgentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSnapshot.ProtoReflect.Descriptor instead.
func (*AgentSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSnapshot) GetMention() string {
	if x != nil {
		return x.Mention
	}
	return ""
}

func (x *AgentSnapshot) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentSnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentSnapshot) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentSnapshot) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *AgentSnapshot) GetModelProfileId() string {
	if x != nil {
		return x.ModelProfileId
	}
	return ""
}

type MessageSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId        string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName      string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderType      SenderType             `protobuf:"varint,4,opt,name=sender_type,json=senderType,proto3,enum=agentroom.runtime.v1.SenderType" json:"sender_type,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DialogueRunId   string                 `protobuf:"bytes,7,opt,name=dialogue_run_id,json=dialogueRunId,proto3" json:"dialogue_run_id,omitempty"`
	TurnIndex       int32                  `protobuf:"varint,8,opt,name=turn_index,json=turnIndex,proto3" json:"turn_index,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,9,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageSnapshot) Reset() {
	*x = MessageSnapshot{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSnapshot) ProtoMessage() {}

func (x *MessageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSnapshot.ProtoReflect.Descriptor instead.
func (*MessageSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageSnapshot) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageSnapshot) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageSnapshot) GetSenderType() SenderType {
	if x != nil {
		return x.SenderType
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *MessageSnapshot) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MessageSnapshot) GetDialogueRunId() string {
	if x != nil {
		return x.DialogueRunId
	}
	return ""
}

func (x *MessageSnapshot) GetTurnIndex() int32 {
	if x != nil {
		return x.TurnIndex
	}
	return 0
}

func (x *MessageSnapshot) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

type KnowledgeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName  string                 `protobuf:"bytes,3,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	ScopeId       string                 `protobuf:"bytes,5,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,6,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeChunk) Reset() {
	*x = KnowledgeChunk{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeChunk) ProtoMessage() {}

func (x *KnowledgeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeChunk.ProtoReflect.Descriptor instead.
func (*KnowledgeChunk) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *KnowledgeChunk) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *KnowledgeChunk) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *KnowledgeChunk) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *KnowledgeChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *KnowledgeChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ModelConnection is sensitive request-only data. Interceptors and application
// logs must never serialize this message or expose api_key.
type ModelConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProfileId     string                 `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelConnection) Reset() {
	*x = ModelConnection{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConnection) ProtoMessage() {}

func (x *ModelConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConnection.ProtoReflect.Descriptor instead.
func (*ModelConnection) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *ModelConnection) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ModelConnection) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ModelConnection) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelConnection) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ModelConnection) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ModelConnection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExecutionLimits struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timeout          *durationpb.Duration   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxOutputBytes   uint32                 `protobuf:"varint,2,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxArtifactBytes uint32                 `protobuf:"varint,3,opt,name=max_artifact_bytes,json=maxArtifactBytes,proto3" json:"max_artifact_bytes,omitempty"`
	MaxToolSteps     uint32                 `protobuf:"varint,4,opt,name=max_tool_steps,json=maxToolSteps,proto3" json:"max_tool_steps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionLimits) Reset() {
	*x = ExecutionLimits{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLimits) ProtoMessage() {}

func (x *ExecutionLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLimits.ProtoReflect.Descriptor instead.
func (*ExecutionLimits) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionLimits) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ExecutionLimits) GetMaxOutputBytes() uint32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *ExecutionLimits) GetMaxArtifactBytes() uint32 {
	if x != nil {
		return x.MaxArtifactBytes
	}
	return 0
}

func (x *ExecutionLimits) GetMaxToolSteps() uint32 {
	if x != nil {
		return x.MaxToolSteps
	}
	return 0
}

type ParticipantSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantSnapshot) Reset() {
	*x = ParticipantSnapshot{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantSnapshot) ProtoMessage() {}

func (x *ParticipantSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantSnapshot.ProtoReflect.Descriptor instead.
func (*ParticipantSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ParticipantSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParticipantSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PromptContextSnapshot carries the complete structured input used by the Go
// Prompt Composer. It intentionally contains no rendered prompt so Python can
// preserve trust boundaries and compose the provider request itself.
type PromptContextSnapshot struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RoomName                  string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	DialogueMode              string                 `protobuf:"bytes,2,opt,name=dialogue_mode,json=dialogueMode,proto3" json:"dialogue_mode,omitempty"`
	OnlineHumanParticipants   []*ParticipantSnapshot `protobuf:"bytes,3,rep,name=online_human_participants,json=onlineHumanParticipants,proto3" json:"online_human_participants,omitempty"`
	RoomAgents                []*AgentSnapshot       `protobuf:"bytes,4,rep,name=room_agents,json=roomAgents,proto3" json:"room_agents,omitempty"`
	TriggerSender             string                 `protobuf:"bytes,5,opt,name=trigger_sender,json=triggerSender,proto3" json:"trigger_sender,omitempty"`
	TriggerSenderType         SenderType             `protobuf:"varint,6,opt,name=trigger_sender_type,json=triggerSenderType,proto3,enum=agentroom.runtime.v1.SenderType" json:"trigger_sender_type,omitempty"`
	TriggerContent            string                 `protobuf:"bytes,7,opt,name=trigger_content,json=triggerContent,proto3" json:"trigger_content,omitempty"`
	LatestVisibleSpeaker      string                 `protobuf:"bytes,8,opt,name=latest_visible_speaker,json=latestVisibleSpeaker,proto3" json:"latest_visible_speaker,omitempty"`
	LatestVisibleSpeakerType  SenderType             `protobuf:"varint,9,opt,name=latest_visible_speaker_type,json=latestVisibleSpeakerType,proto3,enum=agentroom.runtime.v1.SenderType" json:"latest_visible_speaker_type,omitempty"`
	Transcript                []*MessageSnapshot     `protobuf:"bytes,10,rep,name=transcript,proto3" json:"transcript,omitempty"`
	KnowledgeChunks           []*KnowledgeChunk      `protobuf:"bytes,11,rep,name=knowledge_chunks,json=knowledgeChunks,proto3" json:"knowledge_chunks,omitempty"`
	CurrentSpeaker            *AgentSnapshot         `protobuf:"bytes,12,opt,name=current_speaker,json=currentSpeaker,proto3" json:"current_speaker,omitempty"`
	RootHumanTriggerSender    string                 `protobuf:"bytes,13,opt,name=root_human_trigger_sender,json=rootHumanTriggerSender,proto3" json:"root_human_trigger_sender,omitempty"`
	RootHumanTriggerType      SenderType             `protobuf:"varint,14,opt,name=root_human_trigger_type,json=rootHumanTriggerType,proto3,enum=agentroom.runtime.v1.SenderType" json:"root_human_trigger_type,omitempty"`
	RootHumanTriggerContent   string                 `protobuf:"bytes,15,opt,name=root_human_trigger_content,json=rootHumanTriggerContent,proto3" json:"root_human_trigger_content,omitempty"`
	AutonomousTurnIndex       uint32                 `protobuf:"varint,16,opt,name=autonomous_turn_index,json=autonomousTurnIndex,proto3" json:"autonomous_turn_index,omitempty"`
	MaxAutonomousTurns        uint32                 `protobuf:"varint,17,opt,name=max_autonomous_turns,json=maxAutonomousTurns,proto3" json:"max_autonomous_turns,omitempty"`
	AllowSelfFollowup         bool                   `protobuf:"varint,18,opt,name=allow_self_followup,json=allowSelfFollowup,proto3" json:"allow_self_followup,omitempty"`
	AllowAgentToAgentMentions bool                   `protobuf:"varint,19,opt,name=allow_agent_to_agent_mentions,json=allowAgentToAgentMentions,proto3" json:"allow_agent_to_agent_mentions,omitempty"`
	MaxTurnsPerAgent          uint32                 `protobuf:"varint,20,opt,name=max_turns_per_agent,json=maxTurnsPerAgent,proto3" json:"max_turns_per_agent,omitempty"`
	ResponseStrategy          string                 `protobuf:"bytes,21,opt,name=response_strategy,json=responseStrategy,proto3" json:"response_strategy,omitempty"`
	EligiblePeers             []*AgentSnapshot       `protobuf:"bytes,22,rep,name=eligible_peers,json=eligiblePeers,proto3" json:"eligible_peers,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PromptContextSnapshot) Reset() {
	*x = PromptContextSnapshot{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptContextSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptContextSnapshot) ProtoMessage() {}

func (x *PromptContextSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptContextSnapshot.ProtoReflect.Descriptor instead.
func (*PromptContextSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *PromptContextSnapshot) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *PromptContextSnapshot) GetDialogueMode() string {
	if x != nil {
		return x.DialogueMode
	}
	return ""
}

func (x *PromptContextSnapshot) GetOnlineHumanParticipants() []*ParticipantSnapshot {
	if x != nil {
		return x.OnlineHumanParticipants
	}
	return nil
}

func (x *PromptContextSnapshot) GetRoomAgents() []*AgentSnapshot {
	if x != nil {
		return x.RoomAgents
	}
	return nil
}

func (x *PromptContextSnapshot) GetTriggerSender() string {
	if x != nil {
		return x.TriggerSender
	}
	return ""
}

func (x *PromptContextSnapshot) GetTriggerSenderType() SenderType {
	if x != nil {
		return x.TriggerSenderType
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *PromptContextSnapshot) GetTriggerContent() string {
	if x != nil {
		return x.TriggerContent
	}
	return ""
}

func (x *PromptContextSnapshot) GetLatestVisibleSpeaker() string {
	if x != nil {
		return x.LatestVisibleSpeaker
	}
	return ""
}

func (x *PromptContextSnapshot) GetLatestVisibleSpeakerType() SenderType {
	if x != nil {
		return x.LatestVisibleSpeakerType
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *PromptContextSnapshot) GetTranscript() []*MessageSnapshot {
	if x != nil {
		return x.Transcript
	}
	return nil
}

func (x *PromptContextSnapshot) GetKnowledgeChunks() []*KnowledgeChunk {
	if x != nil {
		return x.KnowledgeChunks
	}
	return nil
}

func (x *PromptContextSnapshot) GetCurrentSpeaker() *AgentSnapshot {
	if x != nil {
		return x.CurrentSpeaker
	}
	return nil
}

func (x *PromptContextSnapshot) GetRootHumanTriggerSender() string {
	if x != nil {
		return x.RootHumanTriggerSender
	}
	return ""
}

func (x *PromptContextSnapshot) GetRootHumanTriggerType() SenderType {
	if x != nil {
		return x.RootHumanTriggerType
	}
	return SenderType_SENDER_TYPE_UNSPECIFIED
}

func (x *PromptContextSnapshot) GetRootHumanTriggerContent() string {
	if x != nil {
		return x.RootHumanTriggerContent
	}
	return ""
}

func (x *PromptContextSnapshot) GetAutonomousTurnIndex() uint32 {
	if x != nil {
		return x.AutonomousTurnIndex
	}
	return 0
}

func (x *PromptContextSnapshot) GetMaxAutonomousTurns() uint32 {
	if x != nil {
		return x.MaxAutonomousTurns
	}
	return 0
}

func (x *PromptContextSnapshot) GetAllowSelfFollowup() bool {
	if x != nil {
		return x.AllowSelfFollowup
	}
	return false
}

func (x *PromptContextSnapshot) GetAllowAgentToAgentMentions() bool {
	if x != nil {
		return x.AllowAgentToAgentMentions
	}
	return false
}

func (x *PromptContextSnapshot) GetMaxTurnsPerAgent() uint32 {
	if x != nil {
		return x.MaxTurnsPerAgent
	}
	return 0
}

func (x *PromptContextSnapshot) GetResponseStrategy() string {
	if x != nil {
		return x.ResponseStrategy
	}
	return ""
}

func (x *PromptContextSnapshot) GetEligiblePeers() []*AgentSnapshot {
	if x != nil {
		return x.EligiblePeers
	}
	return nil
}

type ExecuteAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TraceId         string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DialogueRunId   string                 `protobuf:"bytes,4,opt,name=dialogue_run_id,json=dialogueRunId,proto3" json:"dialogue_run_id,omitempty"`
	ExecutorKind    ExecutorKind           `protobuf:"varint,5,opt,name=executor_kind,json=executorKind,proto3,enum=agentroom.runtime.v1.ExecutorKind" json:"executor_kind,omitempty"`
	Room            *RoomSnapshot          `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	Agent           *AgentSnapshot         `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	Trigger         *MessageSnapshot       `protobuf:"bytes,8,opt,name=trigger,proto3" json:"trigger,omitempty"`
	RecentMessages  []*MessageSnapshot     `protobuf:"bytes,9,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	KnowledgeChunks []*KnowledgeChunk      `protobuf:"bytes,10,rep,name=knowledge_chunks,json=knowledgeChunks,proto3" json:"knowledge_chunks,omitempty"`
	Model           *ModelConnection       `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	Limits          *ExecutionLimits       `protobuf:"bytes,12,opt,name=limits,proto3" json:"limits,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PromptContext   *PromptContextSnapshot `protobuf:"bytes,14,opt,name=prompt_context,json=promptContext,proto3" json:"prompt_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteAgentRequest) Reset() {
	*x = ExecuteAgentRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAgentRequest) ProtoMessage() {}

func (x *ExecuteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAgentRequest.ProtoReflect.Descriptor instead.
func (*ExecuteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteAgentRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ExecuteAgentRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteAgentRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecuteAgentRequest) GetDialogueRunId() string {
	if x != nil {
		return x.DialogueRunId
	}
	return ""
}

func (x *ExecuteAgentRequest) GetExecutorKind() ExecutorKind {
	if x != nil {
		return x.ExecutorKind
	}
	return ExecutorKind_EXECUTOR_KIND_UNSPECIFIED
}

func (x *ExecuteAgentRequest) GetRoom() *RoomSnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ExecuteAgentRequest) GetAgent() *AgentSnapshot {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ExecuteAgentRequest) GetTrigger() *MessageSnapshot {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ExecuteAgentRequest) GetRecentMessages() []*MessageSnapshot {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

func (x *ExecuteAgentRequest) GetKnowledgeChunks() []*KnowledgeChunk {
	if x != nil {
		return x.KnowledgeChunks
	}
	return nil
}

func (x *ExecuteAgentRequest) GetModel() *ModelConnection {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *ExecuteAgentRequest) GetLimits() *ExecutionLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ExecuteAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteAgentRequest) GetPromptContext() *PromptContextSnapshot {
	if x != nil {
		return x.PromptContext
	}
	return nil
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ModelAudit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ModelName     string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelAudit) Reset() {
	*x = ModelAudit{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAudit) ProtoMessage() {}

func (x *ModelAudit) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAudit.ProtoReflect.Descriptor instead.
func (*ModelAudit) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ModelAudit) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ModelAudit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ModelAudit) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type KnowledgeSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName  string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSource) Reset() {
	*x = KnowledgeSource{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSource) ProtoMessage() {}

func (x *KnowledgeSource) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSource.ProtoReflect.Descriptor instead.
func (*KnowledgeSource) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *KnowledgeSource) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *KnowledgeSource) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *KnowledgeSource) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ExternalUri   string                 `protobuf:"bytes,7,opt,name=external_uri,json=externalUri,proto3" json:"external_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artifact) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Artifact) GetExternalUri() string {
	if x != nil {
		return x.ExternalUri
	}
	return ""
}

type RunFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          RunErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=agentroom.runtime.v1.RunErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailure) Reset() {
	*x = RunFailure{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailure) ProtoMessage() {}

func (x *RunFailure) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailure.ProtoReflect.Descriptor instead.
func (*RunFailure) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *RunFailure) GetCode() RunErrorCode {
	if x != nil {
		return x.Code
	}
	return RunErrorCode_RUN_ERROR_CODE_UNSPECIFIED
}

func (x *RunFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type AcceptedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedEvent) Reset() {
	*x = AcceptedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedEvent) ProtoMessage() {}

func (x *AcceptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedEvent.ProtoReflect.Descriptor instead.
func (*AcceptedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{14}
}

type ModelStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStartedEvent) Reset() {
	*x = ModelStartedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStartedEvent) ProtoMessage() {}

func (x *ModelStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStartedEvent.ProtoReflect.Descriptor instead.
func (*ModelStartedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *ModelStartedEvent) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type ModelCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCompletedEvent) Reset() {
	*x = ModelCompletedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCompletedEvent) ProtoMessage() {}

func (x *ModelCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCompletedEvent.ProtoReflect.Descriptor instead.
func (*ModelCompletedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *ModelCompletedEvent) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelCompletedEvent) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ToolStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	InputSummary  string                 `protobuf:"bytes,3,opt,name=input_summary,json=inputSummary,proto3" json:"input_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStartedEvent) Reset() {
	*x = ToolStartedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStartedEvent) ProtoMessage() {}

func (x *ToolStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStartedEvent.ProtoReflect.Descriptor instead.
func (*ToolStartedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *ToolStartedEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolStartedEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolStartedEvent) GetInputSummary() string {
	if x != nil {
		return x.InputSummary
	}
	return ""
}

type ToolCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	OutputSummary string                 `protobuf:"bytes,3,opt,name=output_summary,json=outputSummary,proto3" json:"output_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCompletedEvent) Reset() {
	*x = ToolCompletedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCompletedEvent) ProtoMessage() {}

func (x *ToolCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCompletedEvent.ProtoReflect.Descriptor instead.
func (*ToolCompletedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *ToolCompletedEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCompletedEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCompletedEvent) GetOutputSummary() string {
	if x != nil {
		return x.OutputSummary
	}
	return ""
}

type ToolFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Failure       *RunFailure            `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFailedEvent) Reset() {
	*x = ToolFailedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFailedEvent) ProtoMessage() {}

func (x *ToolFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFailedEvent.ProtoReflect.Descriptor instead.
func (*ToolFailedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *ToolFailedEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolFailedEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolFailedEvent) GetFailure() *RunFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type OutputDeltaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputDeltaEvent) Reset() {
	*x = OutputDeltaEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputDeltaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDeltaEvent) ProtoMessage() {}

func (x *OutputDeltaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputDeltaEvent.ProtoReflect.Descriptor instead.
func (*OutputDeltaEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *OutputDeltaEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ArtifactReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactReadyEvent) Reset() {
	*x = ArtifactReadyEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactReadyEvent) ProtoMessage() {}

func (x *ArtifactReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactReadyEvent.ProtoReflect.Descriptor instead.
func (*ArtifactReadyEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *ArtifactReadyEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type CompletedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Artifacts        []*Artifact            `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	KnowledgeSources []*KnowledgeSource     `protobuf:"bytes,3,rep,name=knowledge_sources,json=knowledgeSources,proto3" json:"knowledge_sources,omitempty"`
	Model            *ModelAudit            `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Usage            *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompletedEvent) Reset() {
	*x = CompletedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedEvent) ProtoMessage() {}

func (x *CompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedEvent.ProtoReflect.Descriptor instead.
func (*CompletedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{22}
}

func (x *CompletedEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompletedEvent) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CompletedEvent) GetKnowledgeSources() []*KnowledgeSource {
	if x != nil {
		return x.KnowledgeSources
	}
	return nil
}

func (x *CompletedEvent) GetModel() *ModelAudit {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *CompletedEvent) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type FailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failure       *RunFailure            `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedEvent) Reset() {
	*x = FailedEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedEvent) ProtoMessage() {}

func (x *FailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedEvent.ProtoReflect.Descriptor instead.
func (*FailedEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *FailedEvent) GetFailure() *RunFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type AgentEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Accepted
	//	*AgentEvent_ModelStarted
	//	*AgentEvent_ModelCompleted
	//	*AgentEvent_ToolStarted
	//	*AgentEvent_ToolCompleted
	//	*AgentEvent_ToolFailed
	//	*AgentEvent_OutputDelta
	//	*AgentEvent_ArtifactReady
	//	*AgentEvent_Completed
	//	*AgentEvent_Failed
	Payload       isAgentEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *AgentEvent) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AgentEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetAccepted() *AcceptedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *AgentEvent) GetModelStarted() *ModelStartedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ModelStarted); ok {
			return x.ModelStarted
		}
	}
	return nil
}

func (x *AgentEvent) GetModelCompleted() *ModelCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ModelCompleted); ok {
			return x.ModelCompleted
		}
	}
	return nil
}

func (x *AgentEvent) GetToolStarted() *ToolStartedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ToolStarted); ok {
			return x.ToolStarted
		}
	}
	return nil
}

func (x *AgentEvent) GetToolCompleted() *ToolCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ToolCompleted); ok {
			return x.ToolCompleted
		}
	}
	return nil
}

func (x *AgentEvent) GetToolFailed() *ToolFailedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ToolFailed); ok {
			return x.ToolFailed
		}
	}
	return nil
}

func (x *AgentEvent) GetOutputDelta() *OutputDeltaEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_OutputDelta); ok {
			return x.OutputDelta
		}
	}
	return nil
}

func (x *AgentEvent) GetArtifactReady() *ArtifactReadyEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ArtifactReady); ok {
			return x.ArtifactReady
		}
	}
	return nil
}

func (x *AgentEvent) GetCompleted() *CompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *AgentEvent) GetFailed() *FailedEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Accepted struct {
	Accepted *AcceptedEvent `protobuf:"bytes,10,opt,name=accepted,proto3,oneof"`
}

type AgentEvent_ModelStarted struct {
	ModelStarted *ModelStartedEvent `protobuf:"bytes,11,opt,name=model_started,json=modelStarted,proto3,oneof"`
}

type AgentEvent_ModelCompleted struct {
	ModelCompleted *ModelCompletedEvent `protobuf:"bytes,12,opt,name=model_completed,json=modelCompleted,proto3,oneof"`
}

type AgentEvent_ToolStarted struct {
	ToolStarted *ToolStartedEvent `protobuf:"bytes,13,opt,name=tool_started,json=toolStarted,proto3,oneof"`
}

type AgentEvent_ToolCompleted struct {
	ToolCompleted *ToolCompletedEvent `protobuf:"bytes,14,opt,name=tool_completed,json=toolCompleted,proto3,oneof"`
}

type AgentEvent_ToolFailed struct {
	ToolFailed *ToolFailedEvent `protobuf:"bytes,15,opt,name=tool_failed,json=toolFailed,proto3,oneof"`
}

type AgentEvent_OutputDelta struct {
	OutputDelta *OutputDeltaEvent `protobuf:"bytes,16,opt,name=output_delta,json=outputDelta,proto3,oneof"`
}

type AgentEvent_ArtifactReady struct {
	ArtifactReady *ArtifactReadyEvent `protobuf:"bytes,17,opt,name=artifact_ready,json=artifactReady,proto3,oneof"`
}

type AgentEvent_Completed struct {
	Completed *CompletedEvent `protobuf:"bytes,18,opt,name=completed,proto3,oneof"`
}

type AgentEvent_Failed struct {
	Failed *FailedEvent `protobuf:"bytes,19,opt,name=failed,proto3,oneof"`
}

func (*AgentEvent_Accepted) isAgentEvent_Payload() {}

func (*AgentEvent_ModelStarted) isAgentEvent_Payload() {}

func (*AgentEvent_ModelCompleted) isAgentEvent_Payload() {}

func (*AgentEvent_ToolStarted) isAgentEvent_Payload() {}

func (*AgentEvent_ToolCompleted) isAgentEvent_Payload() {}

func (*AgentEvent_ToolFailed) isAgentEvent_Payload() {}

func (*AgentEvent_OutputDelta) isAgentEvent_Payload() {}

func (*AgentEvent_ArtifactReady) isAgentEvent_Payload() {}

func (*AgentEvent_Completed) isAgentEvent_Payload() {}

func (*AgentEvent_Failed) isAgentEvent_Payload() {}

var File_agent_runtime_v1_agent_runtime_proto protoreflect.FileDescriptor

const file_agent_runtime_v1_agent_runtime_proto_rawDesc = "" +
	"\n" +
	"$agent_runtime/v1/agent_runtime.proto\x12\x14agentroom.runtime.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\fRoomSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdialogue_mode\x18\x03 \x01(\tR\fdialogueMode\"\xec\x01\n" +
	"\rAgentSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amention\x18\x03 \x01(\tR\amention\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rsystem_prompt\x18\x06 \x01(\tR\fsystemPrompt\x12\x18\n" +
	"\aruntime\x18\a \x01(\tR\aruntime\x12(\n" +
	"\x10model_profile_id\x18\b \x01(\tR\x0emodelProfileId\"\xea\x02\n" +
	"\x0fMessageSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12A\n" +
	"\vsender_type\x18\x04 \x01(\x0e2 .agentroom.runtime.v1.SenderTypeR\n" +
	"senderType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12&\n" +
	"\x0fdialogue_run_id\x18\a \x01(\tR\rdialogueRunId\x12\x1d\n" +
	"\n" +
	"turn_index\x18\b \x01(\x05R\tturnIndex\x12*\n" +
	"\x11parent_message_id\x18\t \x01(\tR\x0fparentMessageId\"\xd2\x01\n" +
	"\x0eKnowledgeChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x03 \x01(\tR\fdocumentName\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x19\n" +
	"\bscope_id\x18\x05 \x01(\tR\ascopeId\x12\x1f\n" +
	"\vchunk_index\x18\x06 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"\xb7\x01\n" +
	"\x0fModelConnection\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\xc4\x01\n" +
	"\x0fExecutionLimits\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12(\n" +
	"\x10max_output_bytes\x18\x02 \x01(\rR\x0emaxOutputBytes\x12,\n" +
	"\x12max_artifact_bytes\x18\x03 \x01(\rR\x10maxArtifactBytes\x12$\n" +
	"\x0emax_tool_steps\x18\x04 \x01(\rR\fmaxToolSteps\"9\n" +
	"\x13ParticipantSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf6\n" +
	"\n" +
	"\x15PromptContextSnapshot\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12#\n" +
	"\rdialogue_mode\x18\x02 \x01(\tR\fdialogueMode\x12e\n" +
	"\x19online_human_participants\x18\x03 \x03(\v2).agentroom.runtime.v1.ParticipantSnapshotR\x17onlineHumanParticipants\x12D\n" +
	"\vroom_agents\x18\x04 \x03(\v2#.agentroom.runtime.v1.AgentSnapshotR\n" +
	"roomAgents\x12%\n" +
	"\x0etrigger_sender\x18\x05 \x01(\tR\rtriggerSender\x12P\n" +
	"\x13trigger_sender_type\x18\x06 \x01(\x0e2 .agentroom.runtime.v1.SenderTypeR\x11triggerSenderType\x12'\n" +
	"\x0ftrigger_content\x18\a \x01(\tR\x0etriggerContent\x124\n" +
	"\x16latest_visible_speaker\x18\b \x01(\tR\x14latestVisibleSpeaker\x12_\n" +
	"\x1blatest_visible_speaker_type\x18\t \x01(\x0e2 .agentroom.runtime.v1.SenderTypeR\x18latestVisibleSpeakerType\x12E\n" +
	"\n" +
	"transcript\x18\n" +
	" \x03(\v2%.agentroom.runtime.v1.MessageSnapshotR\n" +
	"transcript\x12O\n" +
	"\x10knowledge_chunks\x18\v \x03(\v2$.agentroom.runtime.v1.KnowledgeChunkR\x0fknowledgeChunks\x12L\n" +
	"\x0fcurrent_speaker\x18\f \x01(\v2#.agentroom.runtime.v1.AgentSnapshotR\x0ecurrentSpeaker\x129\n" +
	"\x19root_human_trigger_sender\x18\r \x01(\tR\x16rootHumanTriggerSender\x12W\n" +
	"\x17root_human_trigger_type\x18\x0e \x01(\x0e2 .agentroom.runtime.v1.SenderTypeR\x14rootHumanTriggerType\x12;\n" +
	"\x1aroot_human_trigger_content\x18\x0f \x01(\tR\x17rootHumanTriggerContent\x122\n" +
	"\x15autonomous_turn_index\x18\x10 \x01(\rR\x13autonomousTurnIndex\x120\n" +
	"\x14max_autonomous_turns\x18\x11 \x01(\rR\x12maxAutonomousTurns\x12.\n" +
	"\x13allow_self_followup\x18\x12 \x01(\bR\x11allowSelfFollowup\x12@\n" +
	"\x1dallow_agent_to_agent_mentions\x18\x13 \x01(\bR\x19allowAgentToAgentMentions\x12-\n" +
	"\x13max_turns_per_agent\x18\x14 \x01(\rR\x10maxTurnsPerAgent\x12+\n" +
	"\x11response_strategy\x18\x15 \x01(\tR\x10responseStrategy\x12J\n" +
	"\x0eeligible_peers\x18\x16 \x03(\v2#.agentroom.runtime.v1.AgentSnapshotR\religiblePeers\"\x9a\a\n" +
	"\x13ExecuteAgentRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12&\n" +
	"\x0fdialogue_run_id\x18\x04 \x01(\tR\rdialogueRunId\x12G\n" +
	"\rexecutor_kind\x18\x05 \x01(\x0e2\".agentroom.runtime.v1.ExecutorKindR\fexecutorKind\x126\n" +
	"\x04room\x18\x06 \x01(\v2\".agentroom.runtime.v1.RoomSnapshotR\x04room\x129\n" +
	"\x05agent\x18\a \x01(\v2#.agentroom.runtime.v1.AgentSnapshotR\x05agent\x12?\n" +
	"\atrigger\x18\b \x01(\v2%.agentroom.runtime.v1.MessageSnapshotR\atrigger\x12N\n" +
	"\x0frecent_messages\x18\t \x03(\v2%.agentroom.runtime.v1.MessageSnapshotR\x0erecentMessages\x12O\n" +
	"\x10knowledge_chunks\x18\n" +
	" \x03(\v2$.agentroom.runtime.v1.KnowledgeChunkR\x0fknowledgeChunks\x12;\n" +
	"\x05model\x18\v \x01(\v2%.agentroom.runtime.v1.ModelConnectionR\x05model\x12=\n" +
	"\x06limits\x18\f \x01(\v2%.agentroom.runtime.v1.ExecutionLimitsR\x06limits\x12S\n" +
	"\bmetadata\x18\r \x03(\v27.agentroom.runtime.v1.ExecuteAgentRequest.MetadataEntryR\bmetadata\x12R\n" +
	"\x0eprompt_context\x18\x0e \x01(\v2+.agentroom.runtime.v1.PromptContextSnapshotR\rpromptContext\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x04R\vtotalTokens\"b\n" +
	"\n" +
	"ModelAudit\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\"m\n" +
	"\x0fKnowledgeSource\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"\xbb\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12!\n" +
	"\fexternal_uri\x18\a \x01(\tR\vexternalUri\"|\n" +
	"\n" +
	"RunFailure\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".agentroom.runtime.v1.RunErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x0f\n" +
	"\rAcceptedEvent\"2\n" +
	"\x11ModelStartedEvent\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"g\n" +
	"\x13ModelCompletedEvent\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x121\n" +
	"\x05usage\x18\x02 \x01(\v2\x1b.agentroom.runtime.v1.UsageR\x05usage\"v\n" +
	"\x10ToolStartedEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12#\n" +
	"\rinput_summary\x18\x03 \x01(\tR\finputSummary\"z\n" +
	"\x12ToolCompletedEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0eoutput_summary\x18\x03 \x01(\tR\routputSummary\"\x8c\x01\n" +
	"\x0fToolFailedEvent\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12:\n" +
	"\afailure\x18\x03 \x01(\v2 .agentroom.runtime.v1.RunFailureR\afailure\"&\n" +
	"\x10OutputDeltaEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"P\n" +
	"\x12ArtifactReadyEvent\x12:\n" +
	"\bartifact\x18\x01 \x01(\v2\x1e.agentroom.runtime.v1.ArtifactR\bartifact\"\xa7\x02\n" +
	"\x0eCompletedEvent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12<\n" +
	"\tartifacts\x18\x02 \x03(\v2\x1e.agentroom.runtime.v1.ArtifactR\tartifacts\x12R\n" +
	"\x11knowledge_sources\x18\x03 \x03(\v2%.agentroom.runtime.v1.KnowledgeSourceR\x10knowledgeSources\x126\n" +
	"\x05model\x18\x04 \x01(\v2 .agentroom.runtime.v1.ModelAuditR\x05model\x121\n" +
	"\x05usage\x18\x05 \x01(\v2\x1b.agentroom.runtime.v1.UsageR\x05usage\"I\n" +
	"\vFailedEvent\x12:\n" +
	"\afailure\x18\x01 \x01(\v2 .agentroom.runtime.v1.RunFailureR\afailure\"\xa8\a\n" +
	"\n" +
	"AgentEvent\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12A\n" +
	"\baccepted\x18\n" +
	" \x01(\v2#.agentroom.runtime.v1.AcceptedEventH\x00R\baccepted\x12N\n" +
	"\rmodel_started\x18\v \x01(\v2'.agentroom.runtime.v1.ModelStartedEventH\x00R\fmodelStarted\x12T\n" +
	"\x0fmodel_completed\x18\f \x01(\v2).agentroom.runtime.v1.ModelCompletedEventH\x00R\x0emodelCompleted\x12K\n" +
	"\ftool_started\x18\r \x01(\v2&.agentroom.runtime.v1.ToolStartedEventH\x00R\vtoolStarted\x12Q\n" +
	"\x0etool_completed\x18\x0e \x01(\v2(.agentroom.runtime.v1.ToolCompletedEventH\x00R\rtoolCompleted\x12H\n" +
	"\vtool_failed\x18\x0f \x01(\v2%.agentroom.runtime.v1.ToolFailedEventH\x00R\n" +
	"toolFailed\x12K\n" +
	"\foutput_delta\x18\x10 \x01(\v2&.agentroom.runtime.v1.OutputDeltaEventH\x00R\voutputDelta\x12Q\n" +
	"\x0eartifact_ready\x18\x11 \x01(\v2(.agentroom.runtime.v1.ArtifactReadyEventH\x00R\rartifactReady\x12D\n" +
	"\tcompleted\x18\x12 \x01(\v2$.agentroom.runtime.v1.CompletedEventH\x00R\tcompleted\x12;\n" +
	"\x06failed\x18\x13 \x01(\v2!.agentroom.runtime.v1.FailedEventH\x00R\x06failedB\t\n" +
	"\apayload*a\n" +
	"\fExecutorKind\x12\x1d\n" +
	"\x19EXECUTOR_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXECUTOR_KIND_LLM\x10\x01\x12\x1b\n" +
	"\x17EXECUTOR_KIND_DEEPAGENT\x10\x02*o\n" +
	"\n" +
	"SenderType\x12\x1b\n" +
	"\x17SENDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SENDER_TYPE_HUMAN\x10\x01\x12\x15\n" +
	"\x11SENDER_TYPE_AGENT\x10\x02\x12\x16\n" +
	"\x12SENDER_TYPE_SYSTEM\x10\x03*\xe5\x03\n" +
	"\fRunErrorCode\x12\x1e\n" +
	"\x1aRUN_ERROR_CODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRUN_ERROR_CODE_INVALID_REQUEST\x10\x01\x12'\n" +
	"#RUN_ERROR_CODE_MODEL_NOT_CONFIGURED\x10\x02\x12.\n" +
	"*RUN_ERROR_CODE_MODEL_AUTHENTICATION_FAILED\x10\x03\x12%\n" +
	"!RUN_ERROR_CODE_MODEL_RATE_LIMITED\x10\x04\x12 \n" +
	"\x1cRUN_ERROR_CODE_MODEL_TIMEOUT\x10\x05\x12\x1c\n" +
	"\x18RUN_ERROR_CODE_CANCELLED\x10\x06\x12\x1e\n" +
	"\x1aRUN_ERROR_CODE_TOOL_FAILED\x10\a\x12!\n" +
	"\x1dRUN_ERROR_CODE_OUTPUT_INVALID\x10\b\x12%\n" +
	"!RUN_ERROR_CODE_RESOURCE_EXHAUSTED\x10\t\x12'\n" +
	"#RUN_ERROR_CODE_EXECUTOR_UNAVAILABLE\x10\n" +
	"\x12!\n" +
	"\x1dRUN_ERROR_CODE_PROTOCOL_ERROR\x10\v\x12\x1b\n" +
	"\x17RUN_ERROR_CODE_INTERNAL\x10\f2t\n" +
	"\x13AgentRuntimeService\x12]\n" +
	"\fExecuteAgent\x12).agentroom.runtime.v1.ExecuteAgentRequest\x1a .agentroom.runtime.v1.AgentEvent0\x01B9Z7agentroom/backend/internal/agentproto/v1;agentruntimev1b\x06proto3"

var (
	file_agent_runtime_v1_agent_runtime_proto_rawDescOnce sync.Once
	file_agent_runtime_v1_agent_runtime_proto_rawDescData []byte
)

func file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP() []byte {
	file_agent_runtime_v1_agent_runtime_proto_rawDescOnce.Do(func() {
		file_agent_runtime_v1_agent_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_runtime_v1_agent_runtime_proto_rawDesc), len(file_agent_runtime_v1_agent_runtime_proto_rawDesc)))
	})
	return file_agent_runtime_v1_agent_runtime_proto_rawDescData
}

var file_agent_runtime_v1_agent_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_runtime_v1_agent_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_agent_runtime_v1_agent_runtime_proto_goTypes = []any{
	(ExecutorKind)(0),             // 0: agentroom.runtime.v1.ExecutorKind
	(SenderType)(0),               // 1: agentroom.runtime.v1.SenderType
	(RunErrorCode)(0),             // 2: agentroom.runtime.v1.RunErrorCode
	(*RoomSnapshot)(nil),          // 3: agentroom.runtime.v1.RoomSnapshot
	(*AgentSnapshot)(nil),         // 4: agentroom.runtime.v1.AgentSnapshot
	(*MessageSnapshot)(nil),       // 5: agentroom.runtime.v1.MessageSnapshot
	(*KnowledgeChunk)(nil),        // 6: agentroom.runtime.v1.KnowledgeChunk
	(*ModelConnection)(nil),       // 7: agentroom.runtime.v1.ModelConnection
	(*ExecutionLimits)(nil),       // 8: agentroom.runtime.v1.ExecutionLimits
	(*ParticipantSnapshot)(nil),   // 9: agentroom.runtime.v1.ParticipantSnapshot
	(*PromptContextSnapshot)(nil), // 10: agentroom.runtime.v1.PromptContextSnapshot
	(*ExecuteAgentRequest)(nil),   // 11: agentroom.runtime.v1.ExecuteAgentRequest
	(*Usage)(nil),                 // 12: agentroom.runtime.v1.Usage
	(*ModelAudit)(nil),            // 13: agentroom.runtime.v1.ModelAudit
	(*KnowledgeSource)(nil),       // 14: agentroom.runtime.v1.KnowledgeSource
	(*Artifact)(nil),              // 15: agentroom.runtime.v1.Artifact
	(*RunFailure)(nil),            // 16: agentroom.runtime.v1.RunFailure
	(*AcceptedEvent)(nil),         // 17: agentroom.runtime.v1.AcceptedEvent
	(*ModelStartedEvent)(nil),     // 18: agentroom.runtime.v1.ModelStartedEvent
	(*ModelCompletedEvent)(nil),   // 19: agentroom.runtime.v1.ModelCompletedEvent
	(*ToolStartedEvent)(nil),      // 20: agentroom.runtime.v1.ToolStartedEvent
	(*ToolCompletedEvent)(nil),    // 21: agentroom.runtime.v1.ToolCompletedEvent
	(*ToolFailedEvent)(nil),       // 22: agentroom.runtime.v1.ToolFailedEvent
	(*OutputDeltaEvent)(nil),      // 23: agentroom.runtime.v1.OutputDeltaEvent
	(*ArtifactReadyEvent)(nil),    // 24: agentroom.runtime.v1.ArtifactReadyEvent
	(*CompletedEvent)(nil),        // 25: agentroom.runtime.v1.CompletedEvent
	(*FailedEvent)(nil),           // 26: agentroom.runtime.v1.FailedEvent
	(*AgentEvent)(nil),            // 27: agentroom.runtime.v1.AgentEvent
	nil,                           // 28: agentroom.runtime.v1.ExecuteAgentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 30: google.protobuf.Duration
}
var file_agent_runtime_v1_agent_runtime_proto_depIdxs = []int32{
	1,  // 0: agentroom.runtime.v1.MessageSnapshot.sender_type:type_name -> agentroom.runtime.v1.SenderType
	29, // 1: agentroom.runtime.v1.MessageSnapshot.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: agentroom.runtime.v1.ExecutionLimits.timeout:type_name -> google.protobuf.Duration
	9,  // 3: agentroom.runtime.v1.PromptContextSnapshot.online_human_participants:type_name -> agentroom.runtime.v1.ParticipantSnapshot
	4,  // 4: agentroom.runtime.v1.PromptContextSnapshot.room_agents:type_name -> agentroom.runtime.v1.AgentSnapshot
	1,  // 5: agentroom.runtime.v1.PromptContextSnapshot.trigger_sender_type:type_name -> agentroom.runtime.v1.SenderType
	1,  // 6: agentroom.runtime.v1.PromptContextSnapshot.latest_visible_speaker_type:type_name -> agentroom.runtime.v1.SenderType
	5,  // 7: agentroom.runtime.v1.PromptContextSnapshot.transcript:type_name -> agentroom.runtime.v1.MessageSnapshot
	6,  // 8: agentroom.runtime.v1.PromptContextSnapshot.knowledge_chunks:type_name -> agentroom.runtime.v1.KnowledgeChunk
	4,  // 9: agentroom.runtime.v1.PromptContextSnapshot.current_speaker:type_name -> agentroom.runtime.v1.AgentSnapshot
	1,  // 10: agentroom.runtime.v1.PromptContextSnapshot.root_human_trigger_type:type_name -> agentroom.runtime.v1.SenderType
	4,  // 11: agentroom.runtime.v1.PromptContextSnapshot.eligible_peers:type_name -> agentroom.runtime.v1.AgentSnapshot
	0,  // 12: agentroom.runtime.v1.ExecuteAgentRequest.executor_kind:type_name -> agentroom.runtime.v1.ExecutorKind
	3,  // 13: agentroom.runtime.v1.ExecuteAgentRequest.room:type_name -> agentroom.runtime.v1.RoomSnapshot
	4,  // 14: agentroom.runtime.v1.ExecuteAgentRequest.agent:type_name -> agentroom.runtime.v1.AgentSnapshot
	5,  // 15: agentroom.runtime.v1.ExecuteAgentRequest.trigger:type_name -> agentroom.runtime.v1.MessageSnapshot
	5,  // 16: agentroom.runtime.v1.ExecuteAgentRequest.recent_messages:type_name -> agentroom.runtime.v1.MessageSnapshot
	6,  // 17: agentroom.runtime.v1.ExecuteAgentRequest.knowledge_chunks:type_name -> agentroom.runtime.v1.KnowledgeChunk
	7,  // 18: agentroom.runtime.v1.ExecuteAgentRequest.model:type_name -> agentroom.runtime.v1.ModelConnection
	8,  // 19: agentroom.runtime.v1.ExecuteAgentRequest.limits:type_name -> agentroom.runtime.v1.ExecutionLimits
	28, // 20: agentroom.runtime.v1.ExecuteAgentRequest.metadata:type_name -> agentroom.runtime.v1.ExecuteAgentRequest.MetadataEntry
	10, // 21: agentroom.runtime.v1.ExecuteAgentRequest.prompt_context:type_name -> agentroom.runtime.v1.PromptContextSnapshot
	2,  // 22: agentroom.runtime.v1.RunFailure.code:type_name -> agentroom.runtime.v1.RunErrorCode
	12, // 23: agentroom.runtime.v1.ModelCompletedEvent.usage:type_name -> agentroom.runtime.v1.Usage
	16, // 24: agentroom.runtime.v1.ToolFailedEvent.failure:type_name -> agentroom.runtime.v1.RunFailure
	15, // 25: agentroom.runtime.v1.ArtifactReadyEvent.artifact:type_name -> agentroom.runtime.v1.Artifact
	15, // 26: agentroom.runtime.v1.CompletedEvent.artifacts:type_name -> agentroom.runtime.v1.Artifact
	14, // 27: agentroom.runtime.v1.CompletedEvent.knowledge_sources:type_name -> agentroom.runtime.v1.KnowledgeSource
	13, // 28: agentroom.runtime.v1.CompletedEvent.model:type_name -> agentroom.runtime.v1.ModelAudit
	12, // 29: agentroom.runtime.v1.CompletedEvent.usage:type_name -> agentroom.runtime.v1.Usage
	16, // 30: agentroom.runtime.v1.FailedEvent.failure:type_name -> agentroom.runtime.v1.RunFailure
	29, // 31: agentroom.runtime.v1.AgentEvent.occurred_at:type_name -> google.protobuf.Timestamp
	17, // 32: agentroom.runtime.v1.AgentEvent.accepted:type_name -> agentroom.runtime.v1.AcceptedEvent
	18, // 33: agentroom.runtime.v1.AgentEvent.model_started:type_name -> agentroom.runtime.v1.ModelStartedEvent
	19, // 34: agentroom.runtime.v1.AgentEvent.model_completed:type_name -> agentroom.runtime.v1.ModelCompletedEvent
	20, // 35: agentroom.runtime.v1.AgentEvent.tool_started:type_name -> agentroom.runtime.v1.ToolStartedEvent
	21, // 36: agentroom.runtime.v1.AgentEvent.tool_completed:type_name -> agentroom.runtime.v1.ToolCompletedEvent
	22, // 37: agentroom.runtime.v1.AgentEvent.tool_failed:type_name -> agentroom.runtime.v1.ToolFailedEvent
	23, // 38: agentroom.runtime.v1.AgentEvent.output_delta:type_name -> agentroom.runtime.v1.OutputDeltaEvent
	24, // 39: agentroom.runtime.v1.AgentEvent.artifact_ready:type_name -> agentroom.runtime.v1.ArtifactReadyEvent
	25, // 40: agentroom.runtime.v1.AgentEvent.completed:type_name -> agentroom.runtime.v1.CompletedEvent
	26, // 41: agentroom.runtime.v1.AgentEvent.failed:type_name -> agentroom.runtime.v1.FailedEvent
	11, // 42: agentroom.runtime.v1.AgentRuntimeService.ExecuteAgent:input_type -> agentroom.runtime.v1.ExecuteAgentRequest
	27, // 43: agentroom.runtime.v1.AgentRuntimeService.ExecuteAgent:output_type -> agentroom.runtime.v1.AgentEvent
	43, // [43:44] is the sub-list for method output_type
	42, // [42:43] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_agent_runtime_v1_agent_runtime_proto_init() }
func file_agent_runtime_v1_agent_runtime_proto_init() {
	if File_agent_runtime_v1_agent_runtime_proto != nil {
		return
	}
	file_agent_runtime_v1_agent_runtime_proto_msgTypes[24].OneofWrappers = []any{
		(*AgentEvent_Accepted)(nil),
		(*AgentEvent_ModelStarted)(nil),
		(*AgentEvent_ModelCompleted)(nil),
		(*AgentEvent_ToolStarted)(nil),
		(*AgentEvent_ToolCompleted)(nil),
		(*AgentEvent_ToolFailed)(nil),
		(*AgentEvent_OutputDelta)(nil),
		(*AgentEvent_ArtifactReady)(nil),
		(*AgentEvent_Completed)(nil),
		(*AgentEvent_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_runtime_v1_agent_runtime_proto_rawDesc), len(file_agent_runtime_v1_agent_runtime_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_runtime_v1_agent_runtime_proto_goTypes,
		DependencyIndexes: file_agent_runtime_v1_agent_runtime_proto_depIdxs,
		EnumInfos:         file_agent_runtime_v1_agent_runtime_proto_enumTypes,
		MessageInfos:      file_agent_runtime_v1_agent_runtime_proto_msgTypes,
	}.Build()
	File_agent_runtime_v1_agent_runtime_proto = out.File
	file_agent_runtime_v1_agent_runtime_proto_goTypes = nil
	file_agent_runtime_v1_agent_runtime_proto_depIdxs = nil
}
