# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from collaboration_runtime.v1 import collaboration_runtime_pb2 as collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collaboration_runtime/v1/collaboration_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollaborationRuntimeServiceStub:
    """CollaborationRuntimeService executes one immutable, multi-turn room
    collaboration. Go remains responsible for persistence and broadcasting.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/agentroom.collaboration.v1.CollaborationRuntimeService/GetCapabilities',
                request_serializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ExecuteConversation = channel.unary_stream(
                '/agentroom.collaboration.v1.CollaborationRuntimeService/ExecuteConversation',
                request_serializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.ExecuteConversationRequest.SerializeToString,
                response_deserializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.CollaborationEvent.FromString,
                _registered_method=True)


class CollaborationRuntimeServiceServicer:
    """CollaborationRuntimeService executes one immutable, multi-turn room
    collaboration. Go remains responsible for persistence and broadcasting.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollaborationRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'ExecuteConversation': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteConversation,
                    request_deserializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.ExecuteConversationRequest.FromString,
                    response_serializer=collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.CollaborationEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentroom.collaboration.v1.CollaborationRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentroom.collaboration.v1.CollaborationRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollaborationRuntimeService:
    """CollaborationRuntimeService executes one immutable, multi-turn room
    collaboration. Go remains responsible for persistence and broadcasting.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentroom.collaboration.v1.CollaborationRuntimeService/GetCapabilities',
            collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesRequest.SerializeToString,
            collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentroom.collaboration.v1.CollaborationRuntimeService/ExecuteConversation',
            collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.ExecuteConversationRequest.SerializeToString,
            collaboration__runtime_dot_v1_dot_collaboration__runtime__pb2.CollaborationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
